gradle/github-release.gradle, gradle/gradle-mvn-push.gradle
Description:
Previous implementation would cache the results of findProperty, we need to use the project version instead, which is updated in the gradle release script.
=> Fix Release script based on .7 release feedback.

core-android/src/main/java/com/uber/sdk/android/core/auth/LoginManager.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java
In case of `LoginManager#onActivityResult()` with an `AuthenticationError.UNAVAILABLE` and `redirectForAuthorizationCode == true`, `LoginManager` automatically falls back to the authorization code grant flow.
However, it *also* incorrectly calls `LoginCallback#onLoginError` with `AuthenticationError.UNAVAILABLE`.
=> Do not return auth error in case of fallback to auth code grant

core-android/src/main/java/com/uber/sdk/android/core/SupportedAppType.java, core-android/src/main/java/com/uber/sdk/android/core/auth/SsoDeeplink.java, core-android/src/main/java/com/uber/sdk/android/core/utils/AppProtocol.java, core-android/src/test/java/com/uber/sdk/android/core/auth/AccessTokenManagerTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/SsoDeeplinkTest.java, core-android/src/test/java/com/uber/sdk/android/core/utils/AppProtocolTest.java, rides-android/src/main/java/com/uber/sdk/android/rides/RideRequestDeeplink.java, rides-android/src/test/java/com/uber/sdk/android/rides/RideRequestDeeplinkTest.java
Description:  Introduces `SupportedAppType` to differentiate the API's of `AppProtocol`.  This adds a public API for `AppProtocol.isInstalled(Context, SupportedAppType)`.  
LoginManager's API is unchanged and will attempt to SSO with Uber apps in the order defined by `SupportedAppType`, Uber then Uber Eats.
Some constants were renamed to explicitly define the app they are defined for.
Related issue(s): #130
=> Adding support to SSO with Uber Eats

README.md, core-android/src/main/java/com/uber/sdk/android/core/auth/LoginManager.java, core-android/src/main/java/com/uber/sdk/android/core/auth/SsoDeeplink.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/SsoDeeplinkTest.java
Description:  Allows SDK configuration to specify the desired application(s) to launch. 
Related issue(s):  #130 and #144
=> Add support for prioritizing SSO Apps

core-android/src/main/java/com/uber/sdk/android/core/auth/LoginActivity.java, core-android/src/main/java/com/uber/sdk/android/core/auth/LoginManager.java, core-android/src/main/java/com/uber/sdk/android/core/auth/SsoDeeplink.java, core-android/src/main/java/com/uber/sdk/android/core/auth/SsoDeeplinkFactory.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginActivityTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/SsoDeeplinkTest.java
Description: Updates `LoginManager` and `LoginActivity` in order to support the new SSO Flow implemented in the mobile apps conforming to [RFC 8252](https://tools.ietf.org/html/rfc8252).
In the new flow `LoginActivity` receives the response from the eater/rider app in `handleResponse` instead of sending it directly to an Activity in the calling application.
Related issue(s): https://github.com/uber/rides-android-sdk/issues/138
Verified to be working in the following scenarios:
| Method | Test Case | Behavior | 
| ------------- | ------------- | --------- |
| `LoginManager.login` | Rides installed (above min RedirectToSdk supported version)  | Successful Login (with redirect to sdk flow) + refresh token |
| `LoginManager.login`  | Rides installed (below RedirectToSdk supported version) | …
=> Update LoginManager to support IETF RFC 8252 compliance

core-android/src/main/java/com/uber/sdk/android/core/auth/LoginManager.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java
Fixed #153
Verified by unit tests.
Description:  Lack of an initial value caused a NPE when `LoginManager#login(Activity)` was invoked.
Related issue(s):  #153
=> Fix NPE caused by unset `productFlowPriority`

core-android/src/main/java/com/uber/sdk/android/core/auth/SsoDeeplink.java
Description: Bumps the minimum Uber Eats version compatible with SSO authentication. This Uber Eats version has fixes for authenticating fresh installs and logged out users.
=> Update minimum Uber Eats version to 2488

core-android/src/main/java/com/uber/sdk/android/core/utils/AppProtocol.java
Description: In the SSO flow, the SDK looks for compatible application packages on the device. Today, it looks for the production & debug packages. This adds support for the nightly package as well.
This is useful as we can distribute nightly packages to partners to verify fixes.
Related issue(s): Addresses #164
=> Introduce compatibility with nightly build

core-android/src/main/java/com/uber/sdk/android/core/utils/CustomTabsHelper.java
Description:
There are some codepaths which could lead to connection being null and when a call is made to `CustomTabsHelper#onDestroy()` it could lead to a `java.lang.IllegalArgumentException`
https://github.com/uber/rides-android-sdk/issues/179
=> fix crash in CustomTabsHelper if connection is null

.github/workflows/build.yml, core-android/src/test/java/com/uber/sdk/android/core/RobolectricTestBase.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LegacyUriRedirectHandlerTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginActivityTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/OAuthWebViewClientTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/SsoDeeplinkTest.java, gradle/dependencies.gradle, rides-android/src/main/java/com/uber/sdk/android/rides/RideRequestActivity.java, rides-android/src/test/java/com/uber/sdk/android/rides/RideRequestActivityTest.java, rides-android/src/test/java/com/uber/sdk/android/rides/RobolectricTestBase.java
Description: Merging in https://github.com/uber/rides-android-sdk/pull/184 caused some tests to break. This was caused by a runtime issue that could not find the resources for instrumented tests. For some reason this worked on Android Studio.
Regardless, the fix is to bump the version of RoboElectric so that it can instrument and find the resources. 
There is also a secondary issue that is caused by the migration to the new android emulator runner. See the linked issue below. I have removed the 29 and 30 api for this reason (even though we only target 28).
=> Fixing Tests Associated With AndroidX

core-android/src/main/java/com/uber/sdk/android/core/auth/LoginActivity.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginActivityTest.java
Description: Closes #204 
In edge cases where we received a replayed response from the server for PAR then we would end up calling remove progress indicator twice when it is already null thereby crashing the application.
Added a null check guard before getting the parent of progressIndicator.
=> Added failsafe null check when removing progress indicator

README.md, authentication/build.gradle.kts, authentication/src/main/AndroidManifest.xml, build.gradle.kts, core-android/build.gradle.kts, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, rides-android/build.gradle.kts, samples/login-sample/build.gradle.kts, samples/login-with-auth-code-demo/build.gradle.kts, samples/request-button-sample/build.gradle.kts, settings.gradle.kts, spotless/copyright.java, spotless/copyright.kt
- added splotless plugin
- upgraded gradle to latest (8.6)
- upgraded android gradle pluign to 8.2 to support 34 targetSdk
- added copyright files to add a license header to all source files
=> Added spotless plugin for code formatting

authentication/build.gradle.kts, authentication/src/main/kotlin/com/uber/sdk2/auth/api/request/AuthContext.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/request/AuthDestination.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/request/AuthType.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/request/CrossApp.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/request/PrefillInfo.kt, build.gradle.kts, core/src/main/kotlin/com/uber/sdk2/core/utils/CustomTabsHelper.kt, gradle/libs.versions.toml, settings.gradle.kts
Description:
Added support for parcelable in the authentication module. The auth request and config objects need to be parcelable to enable launching the AuthActivity with the relevant AuthContext object.
This diff 
- Makes AuthContext, AuthDestination, AuthType, CrossApp and PrefillInfo parcelable
- Fixed a couple of bugs in CustomTabsHelper
=> Adding parcelize

authentication/build.gradle.kts, authentication/src/main/kotlin/com/uber/sdk2/auth/api/AppDiscovering.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/AuthProviding.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/PKCEGenerator.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/exception/AuthException.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/request/SsoConfig.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/response/AuthResult.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/response/PARResponse.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/response/UberToken.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/api/sso/SsoLink.kt
A few more classes added for scaffolding of the sdk. 
AppDiscovery: uses the app priority defined by the third party app to discover the best app to handle the sso flow
AuthProvider - Executes the sso flow
PARResponse - Holds a request_uri and it's expiration which can be sent to the backend as a query param for prefilling the profile information of the user
PKCEGenerator - Abstraction for generating a code challenge and verifier pair
=> Added abstractions for AppDiscovery and AuthProvider

authentication/src/main/kotlin/com/uber/sdk2/auth/api/AuthProviding.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/AuthProvider.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/PKCEGeneratorImpl.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/service/AuthService.kt, authentication/src/test/kotlin/com/uber/sdk2/auth/internal/AuthProviderTest.kt, authentication/src/test/kotlin/com/uber/sdk2/auth/internal/PKCEGeneratorImplTest.kt, authentication/src/test/kotlin/com/uber/sdk2/auth/internal/shadow/ShadowSsoConfigProvider.kt, authentication/src/test/kotlin/com/uber/sdk2/auth/internal/shadow/ShadowSsoLinkFactory.kt
Added AuthProvider to initiate the authentication flow by performing PAR if the prefill information is available otherwise directly invoke the sso link to perform SSO based on the app prioritization or inApp (custom tabs) flow.
When the sso flow is complete we receive an authCode. Depending on the type of auth requested we take the next step
- PKCE: perform token exchange via proof key code exchange protocol using the authCode received
- AuthCode: return the authCode in the UberToken object back to the caller
Added a couple of shadow classes to help with unit testing and added unit tests for AuthProvider and PKCEGeneratorImpl
=> Added AuthProvider implementation

authentication/src/main/kotlin/com/uber/sdk2/auth/internal/sso/UniversalSsoLink.kt, authentication/src/test/kotlin/com/uber/sdk2/auth/internal/sso/UniversalSsoLinkTest.kt
When optional query parameters were passed the uri wasn't updated with these params. This PR fixes the issue and adds unit test to verify the query params in the uri
=> Update uri when adding optional query parameters

authentication/src/main/kotlin/com/uber/sdk2/auth/api/exception/AuthException.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/sso/UniversalSsoLink.kt
If the SSO with cross app flow does not work out due to some error then we need to propagate the same error back to the client. The previous implementation consumed the error and emitted just as canceled but there could be something wrong like bad redirect_uri or scope etc. so we want to be able to provide the right message to the caller
=> Propagate the error message for failed sso back to the caller

authentication/build.gradle.kts, authentication/src/main/AndroidManifest.xml, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/AuthActivity.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/request/AuthContext.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/request/CrossApp.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/request/PrefillInfo.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/request/SsoConfig.kt, gradle.properties
This PR addressess:
• When inApp auth mode is used and canceled the user would end up on empty screen because the AuthActivity never finished
• Added @JvmOverloads annotation to some data classes if there are consumers using java they can only pass the parameters needed
• updated the sdk package to com.uber.sdk2
=> Some minor fixes

authentication/src/main/kotlin/com/uber/sdk2/auth/internal/sso/UniversalSsoLink.kt, core/build.gradle.kts, core/src/main/kotlin/com/uber/sdk2/core/config/UriConfig.kt, core/src/test/kotlin/com/uber/sdk2/core/RobolectricTestBase.kt, core/src/test/kotlin/com/uber/sdk2/core/UriConfigTest.kt
Description:
When launching the authorization flow we add a bunch of query parameters including a `code_challenge` which is part of the PKCE flow https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-pkce
There were some recent changes made on the backend to adhere to the pkce spec which required adding `code_challenge_method` as a query param from the callers. The sdk wasn't doing that before which resulted in invalid grant type error. So, adding the required parameter to comply with the spec.
=> Added code challenge method as a query param

authentication/build.gradle.kts, authentication/gradle.properties, authentication/src/main/kotlin/com/uber/sdk2/auth/AuthProviding.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/AuthActivity.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/AuthProvider.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/sso/UniversalSsoLink.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/sso/SsoLink.kt, core/src/main/kotlin/com/uber/sdk2/core/config/UriConfig.kt, gradle.properties
There are a couple of ways of performing authentication - sso via an Uber app or sso via custom tabs. There's a subtle difference in the implementation - with custom tabs the authCode is returned via the intent's data inside onNewIntent() callback. Whereas, for sso via app the authCode is returned via activity result listener. A bug got introduced when adding code to finish the `AuthActivity` inside onResume() when the intent's data is null.
When the auth flow is launched in custom tabs and the intent data is null we need to finish the AuthActivity. But, this is also true when performing sso via any of the Uber apps. When the auth is finished in an Uber app we get back the result in the `AuthActivity` and it is resumed with `intent.data = null`. Due to this, the `AuthActivity` finished …
=> Fixed bug with authentication flow

authentication/src/main/kotlin/com/uber/sdk2/auth/internal/sso/UniversalSsoLink.kt, authentication/src/test/kotlin/com/uber/sdk2/auth/internal/sso/UniversalSsoLinkTest.kt, core/src/main/kotlin/com/uber/sdk2/core/config/UriConfig.kt, core/src/test/kotlin/com/uber/sdk2/core/UriConfigTest.kt
The consumer apps can use different authentication mechanisms to authenticate against Uber - using an Uber app or using inApp flow (leveraging custom tabs). We use the same app link for both forms of authentication
If the authentication flow is chosen as `inApp` but there's an Uber app installed that is capable of intercepting the app link then it is possible that in the middle of the `inApp` flow an Uber app gets launched due to a redirect from the web.
For `inApp` flow we use a different url from the url for Uber app sso flow. For sso the path is `oauth/v2/universal/authorize` but for `inApp` the path is `oauth/v2/authorize`. This ensures that no app can intercept the redirect from the web and user can successfully complete the flow on web.
=> Fixed bug with inApp authentication

authentication/src/main/kotlin/com/uber/sdk2/auth/internal/AuthProvider.kt, authentication/src/test/kotlin/com/uber/sdk2/auth/internal/AuthProviderTest.kt, core/src/main/kotlin/com/uber/sdk2/core/config/UriConfig.kt, core/src/test/kotlin/com/uber/sdk2/core/UriConfigTest.kt
If the code challenge param is added for authType = AuthCode then backend expects a code verifier too. This blocks clients who are using the 3-legged oauth flow using oauth client secret since they do not have a code verifier.
So, this param should not be sent for AuthCode auth type.
=> Add code challenge param only with pkce authType

authentication/src/main/kotlin/com/uber/sdk2/auth/internal/AuthProvider.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/request/AuthContext.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/request/Prompt.kt, authentication/src/test/kotlin/com/uber/sdk2/auth/internal/AuthProviderTest.kt, core/src/main/kotlin/com/uber/sdk2/core/config/UriConfig.kt
Description:
As per the openid [spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest:~:text=select_account-,The,-Authorization%20Server%20SHOULD) a prompt parameter could be added to the url to present an appropriate webpage to the user. It can be used to force user to login again or provide consent etc. This change adds currently supported values of the `prompt` parameter to the sdk. We will update the sdk when Uber backend supports other values
=> Added prompt parameter for sso authorization

authentication/src/main/kotlin/com/uber/sdk2/auth/AuthProviding.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/AuthActivity.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/AuthProvider.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/internal/sso/UniversalSsoLink.kt, authentication/src/main/kotlin/com/uber/sdk2/auth/sso/SsoLink.kt
Previously we were resulting on startActivityForResult to invoke an Uber app for sso. This results in subpar UX and is buggy because it creates a new instance of the Uber app's activity which shows on top of the third party's app stack. So, we are changing the implementation a little big and returning the result via redirect uri that was passed using the sso_config.json configuration from the third party app.
The authCode will be passed in the fragment of the redirect uri as mentioned in this [RFC](https://datatracker.ietf.org/doc/html/rfc6749) 
The authCode will only be returned if all other config information that was setup on the Uber developer dash for the third party app matches with the authorization request.
This does not change the integration point of the calling app but is a …
=> Switching to use startActivity with flags instead of startActivityForResult
