sdk/src/test/java/com/uber/sdk/android/rides/UberSdkTest.java
Applies ``s/Exceptoin/Exception/`` spelling correction.
=> Fix typos in UberSdkTest.java

README.md
The README example code for Ride Request Button contains a few errors that prevent it from working, some typos and a failure to set the client id.
=> Fix Ride Request Button example in README.

gradle.properties
Description:
Addressing Zac's feedback on pom dev name and id
=> Changing dev name and id to Uber

CHANGELOG.md, README.md, core-android/src/main/java/com/uber/sdk/android/core/auth/LoginButton.java, core-android/src/main/java/com/uber/sdk/android/core/auth/LoginManager.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginButtonTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java, rides-android/src/main/java/com/uber/sdk/android/rides/RideRequestActivity.java, rides-android/src/main/java/com/uber/sdk/android/rides/RideRequestActivityBehavior.java, rides-android/src/test/java/com/uber/sdk/android/rides/RideRequestActivityTest.java, samples/login-sample/src/main/java/com/uber/sdk/android/samples/LoginSampleActivity.java, samples/request-button-sample/src/main/java/com/uber/sdk/android/rides/samples/SampleActivity.java
=> Migrate uses of AccessTokenMigration to AccessTokenStorage

CHANGELOG.md, core-android/src/main/java/com/uber/sdk/android/core/auth/LoginActivity.java, rides-android/src/main/java/com/uber/sdk/android/rides/RideRequestView.java
=> Add deprecated member "onReceivedError" to solve compatibility issue

CHANGELOG.md, build.gradle, gradle/github-release.gradle, samples/login-sample/build.gradle, samples/request-button-sample/build.gradle
Description:
- Sets task ordering for the release notes generation to enforce appropriate ordering.
- Updated Sample apps to generate correct and buildable zip, broken last major build.gradle refactoring
#115
=> Fix release notes versioning and sample artifact generation

CHANGELOG.md, gradle/dependencies.gradle
Description:
Updating to downstream dependency with various fixes.
=> Update Java SDK dependency to 0.8.0

README.md
=> Fix redirect uri readme

README.md
On 0.9.1 this seems to be the method to use
=> Rename `setAuthCodeEnabled` to `setAuthCodeFlowEnabled`

.travis.yml, core-android/src/main/java/com/uber/sdk/android/core/utils/Preconditions.java
Description:  Updates travis configuration to accept necessary licenses.
Related issue(s):  #132
=> Update travis config to accept updated license

build.gradle, core-android/build.gradle, gradle/dependencies.gradle, gradle/gradle-mvn-push.gradle, gradle/wrapper/gradle-wrapper.properties, rides-android/build.gradle, samples/login-sample/build.gradle, samples/request-button-sample/build.gradle
Description:  Gradle and it's associated plugin need an update.  The plugin version `2.3.0` issues a bunch of noisy NDK warnings every build.  
Related issue(s):  #134
=> Update Gradle to 4.4, Gradle Plugin to 3.0.0

core-android/src/main/java/com/uber/sdk/android/core/auth/SsoDeeplink.java
Description: Bump the minimum supported eats version to current version
=> Bump minimum supported eats version

.travis.yml, core-android/src/main/java/com/uber/sdk/android/core/auth/LoginManager.java, core-android/src/main/java/com/uber/sdk/android/core/auth/SsoDeeplink.java, core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java, core-android/src/test/java/com/uber/sdk/android/core/auth/SsoDeeplinkTest.java
Scopes or CustomScopes is now allowed.
Description:  There are now usages that call for ONLY using custom scopes that this unblocks.
Related issue(s):  #151
=> Loosening requirement of Scopes for Login.  

core-android/src/main/java/com/uber/sdk/android/core/auth/AuthUtils.java, core-android/src/main/java/com/uber/sdk/android/core/auth/LoginActivity.java, core-android/src/test/java/com/uber/sdk/android/core/auth/AuthUtilsTest.java
fixes #159
Description:  SDK is expected to pass Auth Code to app and app developer is expected to use their own service to exchange auth code for access token.  
Related issue(s): #159
=> Handle redirect for ChromeTab Auth Code flow.

.gitignore, core-android/src/main/java/com/uber/sdk/android/core/auth/LoginActivity.java, core-android/src/main/java/com/uber/sdk/android/core/utils/CustomTabsHelper.java
=> Fix service connection

.github/workflows/build.yml
This may fix the snapshot uploading.
Also, I made some small adjustments to match the style in comparison with other Uber projects
=> Change how the auth data is published into the config yaml

gradle.properties
bumping up to next version - v0.10.5-SNAPSHOT
=> bumping up the version to prepare for next release

CHANGELOG.md, gradle.properties, gradle/dependencies.gradle
Updated [rides-java-sdk](https://github.com/uber/rides-java-sdk) version to 0.8.4
updated changelog and gradle.properties
=> updated rides java sdk to 0.8.4

gradle.properties, gradle/dependencies.gradle
=> preparing for release

.buildscript/deploy_snapshot.sh, .github/workflows/build.yml, gradle.properties
The repo's master branch was renamed to main so making relevant changes to point to main branch
=> renaming master to main

core/build.gradle.kts, core/src/main/kotlin/com/uber/sdk2/core/ui/UberButton.kt, core/src/main/kotlin/com/uber/sdk2/core/ui/legacy/UberButton.kt, gradle/libs.versions.toml, settings.gradle.kts
Moved the previous implementation to legacy package and added a new UberButton in compose
=> Added UberButton in compose

authentication/gradle.properties, gradle.properties
changing the auth module versioning to 2.0 rest of the modules are still at 0.10.11-SNAPSHOT
=> Updating versions of the modules
